export * from './valor-desejado/valor-desejado'
export * from './cadastro-dados/cadastro-dados'
export * from './cadastro-login/cadastro-login'
export * from './editar-email/editar-email'
export * from './confirmacao-solicitacao/confirmacao-solicitacao'
